spring:
  profiles:
    active: dev
---
server:
  port: 8888

spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
eureka:
  client:
    service-url:
      defaultZone: http://yiqiandewo1:7001/eureka/,http://yiqiandewo2:7002/eureka/

---
server:
  port: 8889
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
eureka:
  client:
    service-url:
      defaultZone: http://yiqiandewo1:7001/eureka/,http://yiqiandewo2:7002/eureka/